language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

git:
  depth: 5

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - flags="--no-interaction --no-progress --prefer-dist"
  - if [ `phpenv version-name` == "5.3.3" ]; then flags="--ignore-platform-reqs $flags"; fi

install:
  - composer install $flags

script:
  - vendor/bin/phpunit
